### ISSUE TITLE
Stackable Item in Inventory

### ISSUE THREAD

**Issue by CubBossa** [MCMDEV/i18n#5]
Hey, I love the idea but always stumble about the problem with stackable items. Once rendered, two translated items would only be stackable if in the same language, right? So items like currency that people actually drop to each other could not use the system.

I thought about it and whats needed is a mechanism to recognize a rendered component as a serverside translatable component.
What I came up with is using the vanilla translation key
```json
"createWorld.customize.flat.layer": "%s",
```

One could send it with the key as seccond argument and rendering as first argument. It would render just as supposed to, but then when this particular key is being send to the server, its first argument will be set to Component.empty() to make items stackable again.

It brings in a bit of extra work for the server though. What are your thoughts?

**Comment by CubBossa** [comment]
I have a translation framework that focusses on MiniMessage and file generation and styles and all that and works great in combination with yours as it also uses GlobalTranslator, its called TinyTranslations. Thats how I ended up here

**Comment by mcmdev** [comment]
This plugin doesn't actually change items serverside. It uses ProtocolLib to just render the items in the packets

**Comment by CubBossa** [comment]
Yeah but when your server sends a modified packet to client, the client sends the modified itemstack back. Saying "I picked up itemstack xy". Afaik there are issues because items are compared via nbt and then name differs. Server side its a translatable and clientside its a rendered component

**Comment by mcmdev** [comment]
Only in creative mode, where the client sends a [Creative Mode Slot](https://wiki.vg/Protocol#Set_Creative_Mode_Slot) packet.
This could be fixed by adding the original name as a second tag, then when the Creative Mode Slot packet is received the name is replaced with original name from the custom tag.

I don't want to do any custom NBT business with this plugin though, it's just supposed to apply Adventure translations on a packet level.
